# Generated by Django 3.1.7 on 2021-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminID',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='voterID',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
