# Generated by Django 3.1.7 on 2021-04-11 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0002_auto_20210411_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boothID', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=16)),
                ('active', models.BooleanField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_as_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
