# Generated by Django 3.1.7 on 2021-04-11 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0003_booth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boothID', models.CharField(max_length=16)),
                ('candidateID', models.CharField(max_length=16)),
                ('candidateName', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='adminID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='voterID',
        ),
        migrations.CreateModel(
            name='VotingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boothID', models.CharField(max_length=16)),
                ('candidateID', models.CharField(max_length=16)),
                ('voterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_voted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boothID', models.CharField(max_length=16)),
                ('allowed', models.BooleanField()),
                ('voterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_in_voterlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
