# Generated by Django 3.1.7 on 2021-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0004_auto_20210411_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='allowed',
        ),
        migrations.AddField(
            model_name='voter',
            name='voting_status',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
