# Generated by Django 3.1.7 on 2021-04-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0008_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.ImageField(default=None, upload_to='images/user'),
            preserve_default=False,
        ),
    ]
