# Generated by Django 3.1.7 on 2021-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0012_auto_20210413_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='voted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
