# Generated by Django 3.1.7 on 2021-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0015_auto_20210414_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='voting_status',
            field=models.CharField(default='Not Voted', max_length=16),
        ),
    ]
