# Generated by Django 3.1.7 on 2021-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0017_booth_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(default='NA', upload_to='images/candidates'),
            preserve_default=False,
        ),
    ]
