# Generated by Django 3.1.7 on 2021-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbvs', '0019_auto_20210417_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/candidates'),
        ),
    ]
